### ISSUE TITLE
why it's on tinydb

### ISSUE THREAD

**Issue by root-7325** [NyanAlex/old-stars#1]
why it's just reupload of cb v1

**Comment by LeonardDev** [comment]
Блять, ну перепиши на монго

**Comment by root-7325** [comment]
ты это говоришь будто это очень сложно
и это все ещё не ответило на первый вопрос

**Comment by LeonardDev** [comment]
Как минимум я не говорил, что сложно, а тем более я писал

**Comment by root-7325** [comment]
Ну так вопрос то все еще прежний
Зачем этот перезалив с добавлением себя как автора? Столько времени прошло - ни одного апдейта

**Comment by root-7325** [comment]
Land
